[28-Feb-2018 07:58:29] #### UPDATE TO v5.000 STARTED
[28-Feb-2018 07:58:29] Updated: /var/sites/b/bromleybr.co.uk/public_html/bsjc/ext/modules/payment/paypal/express.php
[28-Feb-2018 07:58:29] Updated: /var/sites/b/bromleybr.co.uk/public_html/bsjc/includes/apps/paypal/admin/actions/balance/retrieve.php
[28-Feb-2018 07:58:29] Updated: /var/sites/b/bromleybr.co.uk/public_html/bsjc/includes/apps/paypal/admin/actions/credentials/process.php
[28-Feb-2018 07:58:29] Updated: /var/sites/b/bromleybr.co.uk/public_html/bsjc/includes/apps/paypal/admin/actions/credentials.php
[28-Feb-2018 07:58:29] Updated: /var/sites/b/bromleybr.co.uk/public_html/bsjc/includes/apps/paypal/admin/actions/start/process.php
[28-Feb-2018 07:58:29] Updated: /var/sites/b/bromleybr.co.uk/public_html/bsjc/includes/apps/paypal/admin/actions/start/retrieve.php
[28-Feb-2018 07:58:29] Updated: /var/sites/b/bromleybr.co.uk/public_html/bsjc/includes/apps/paypal/admin/content/credentials.php
[28-Feb-2018 07:58:29] Updated: /var/sites/b/bromleybr.co.uk/public_html/bsjc/includes/apps/paypal/admin/content/privacy.php
[28-Feb-2018 07:58:29] Updated: /var/sites/b/bromleybr.co.uk/public_html/bsjc/includes/apps/paypal/admin/content/start.php
[28-Feb-2018 07:58:29] Updated: /var/sites/b/bromleybr.co.uk/public_html/bsjc/includes/apps/paypal/api/BMCreateButton.php
[28-Feb-2018 07:58:29] Updated: /var/sites/b/bromleybr.co.uk/public_html/bsjc/includes/apps/paypal/hooks/admin/orders/tab.php
[28-Feb-2018 07:58:29] Updated: /var/sites/b/bromleybr.co.uk/public_html/bsjc/includes/apps/paypal/languages/english/admin/credentials.php
[28-Feb-2018 07:58:29] Updated: /var/sites/b/bromleybr.co.uk/public_html/bsjc/includes/apps/paypal/languages/english/admin/privacy.php
[28-Feb-2018 07:58:29] Updated: /var/sites/b/bromleybr.co.uk/public_html/bsjc/includes/apps/paypal/languages/english/modules/EC/cfg_params/checkout_flow.php
[28-Feb-2018 07:58:29] Updated: /var/sites/b/bromleybr.co.uk/public_html/bsjc/includes/apps/paypal/languages/english/modules/EC/cfg_params/incontext_button_color.php
[28-Feb-2018 07:58:29] Updated: /var/sites/b/bromleybr.co.uk/public_html/bsjc/includes/apps/paypal/languages/english/modules/EC/cfg_params/incontext_button_shape.php
[28-Feb-2018 07:58:29] Updated: /var/sites/b/bromleybr.co.uk/public_html/bsjc/includes/apps/paypal/languages/english/modules/EC/cfg_params/incontext_button_size.php
[28-Feb-2018 07:58:29] Updated: /var/sites/b/bromleybr.co.uk/public_html/bsjc/includes/apps/paypal/languages/english/modules/LOGIN/LOGIN.php
[28-Feb-2018 07:58:29] Updated: /var/sites/b/bromleybr.co.uk/public_html/bsjc/includes/apps/paypal/modules/DP/api/DoDirectPayment.php
[28-Feb-2018 07:58:29] Updated: /var/sites/b/bromleybr.co.uk/public_html/bsjc/includes/apps/paypal/modules/DP/api/PayflowPayment.php
[28-Feb-2018 07:58:29] Updated: /var/sites/b/bromleybr.co.uk/public_html/bsjc/includes/apps/paypal/modules/DP/DP.php
[28-Feb-2018 07:58:29] Updated: /var/sites/b/bromleybr.co.uk/public_html/bsjc/includes/apps/paypal/modules/EC/api/DoExpressCheckoutPayment.php
[28-Feb-2018 07:58:29] Updated: /var/sites/b/bromleybr.co.uk/public_html/bsjc/includes/apps/paypal/modules/EC/api/PayflowDoExpressCheckoutPayment.php
[28-Feb-2018 07:58:29] Updated: /var/sites/b/bromleybr.co.uk/public_html/bsjc/includes/apps/paypal/modules/EC/cfg_params/checkout_flow.php
[28-Feb-2018 07:58:29] Updated: /var/sites/b/bromleybr.co.uk/public_html/bsjc/includes/apps/paypal/modules/EC/cfg_params/incontext_button_color.php
[28-Feb-2018 07:58:29] Updated: /var/sites/b/bromleybr.co.uk/public_html/bsjc/includes/apps/paypal/modules/EC/cfg_params/incontext_button_shape.php
[28-Feb-2018 07:58:29] Updated: /var/sites/b/bromleybr.co.uk/public_html/bsjc/includes/apps/paypal/modules/EC/cfg_params/incontext_button_size.php
[28-Feb-2018 07:58:29] Updated: /var/sites/b/bromleybr.co.uk/public_html/bsjc/includes/apps/paypal/modules/EC/cfg_params/transaction_method.php
[28-Feb-2018 07:58:29] Updated: /var/sites/b/bromleybr.co.uk/public_html/bsjc/includes/apps/paypal/modules/EC/EC.php
[28-Feb-2018 07:58:29] Updated: /var/sites/b/bromleybr.co.uk/public_html/bsjc/includes/apps/paypal/modules/HS/HS.php
[28-Feb-2018 07:58:29] Updated: /var/sites/b/bromleybr.co.uk/public_html/bsjc/includes/apps/paypal/modules/LOGIN/api/UserInfo.php
[28-Feb-2018 07:58:29] Updated: /var/sites/b/bromleybr.co.uk/public_html/bsjc/includes/apps/paypal/modules/LOGIN/LOGIN.php
[28-Feb-2018 07:58:29] Updated: /var/sites/b/bromleybr.co.uk/public_html/bsjc/includes/apps/paypal/modules/PS/cfg_params/prepare_order_status_id.php
[28-Feb-2018 07:58:29] Updated: /var/sites/b/bromleybr.co.uk/public_html/bsjc/includes/apps/paypal/OSCOM_PayPal.php
[28-Feb-2018 07:58:29] Updated: /var/sites/b/bromleybr.co.uk/public_html/bsjc/includes/apps/paypal/version.txt
[28-Feb-2018 07:58:29] Updated: /var/sites/b/bromleybr.co.uk/public_html/bsjc/includes/modules/payment/paypal_express.php
[28-Feb-2018 07:58:29] Updated: /var/sites/b/bromleybr.co.uk/public_html/bsjc/includes/modules/payment/paypal_standard.php
[28-Feb-2018 07:58:29] Updated: /var/sites/b/bromleybr.co.uk/public_html/bsjc/includes/apps/paypal/version.txt
[28-Feb-2018 07:58:29] #### UPDATE TO v5.000 COMPLETED
